// File generated by Gemini CLI based on project configuration.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNjDjkV3lUOM_iCKYaHGemg9ddJrlP_5I',
    appId: '1:685968369147:web:dfc68325d12b5acaf1975e',
    messagingSenderId: '685968369147',
    projectId: 'turfy-7e791',
    authDomain: 'turfy-7e791.firebaseapp.com',
    storageBucket: 'turfy-7e791.firebasestorage.app',
    measurementId: 'G-Y6RFE9PE9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnoWJ77P32ZSnpVKf1tpeEPGPlVphFklY',
    appId: '1:685968369147:android:a71dfff6228074f7f1975e',
    messagingSenderId: '685968369147',
    projectId: 'turfy-7e791',
    storageBucket: 'turfy-7e791.firebasestorage.app',
  );
}
